{% set version = "1.16" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-corrgram
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/corrgram_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/corrgram/corrgram_{{ version }}.tar.gz
  sha256: 1078904c866ef319325b5fb0a0e0ad0d00dea0c22f6169ddc2f33b3e5dcd2278

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ellipse
    - r-lattice
  run:
    - r-base
    - r-ellipse
    - r-lattice

test:
  commands:
    - $R -e "library('corrgram')"           # [not win]
    - "\"%R%\" -e \"library('corrgram')\""  # [win]

about:
  home: https://kwstat.github.io/corrgram/
  dev_url: https://github.com/kwstat/corrgram
  license: MIT
  summary: Calculates correlation of variables and displays the results graphically. Included panel functions can display points, shading, ellipses, and correlation values with confidence intervals. See Friendly (2002) <doi:10.1198/000313002533>.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT

extra:
  recipe-maintainers:
    - conda-forge/r
