appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: FK2EfptNXAIxtZKjKm6qLwpTL3uS9IslYUvXUUrWlplk6OZnOrq/9X2YWQduKSgMB6ScT+UCvH5jsOQJ/NUlOVJ74sXm5CP+crUOYM8eThvxvOK12TbrR+xZ72HKu2uh1JVJk+x6UYI9S51FTdy8h71DpSGaDsZAz82erpPZ7B5Ea56OsW7PDCwyfMqVFx0REcDBIdG454IqHop72tV+eEMyH/iMvsgSdjFh7stmkf09QQ4UvSVLX9ZjZeNuIE9RfayA6J11lWP3SIZfVSkItzEMZxovm2jH0iupC871G0FP9YufQbCNHFMNOKLP4QkjiT7HcgvH/aBo1kRJc3A8h0rPobf5Ms+8BiAIoFXLjq7mb+OXYCVp8Ljfb0HlC8cTCj9DxZWBiP/Ijk29AUJmpFtOe01bHGfAd2kzxunXgSTTEy7XzUBYiOYinN3nyttEyne10VyXqrIxjclS9FywCa94NAg6192OQzOfU2n1kfcdwboW1fsGEljTBY2lO/Hj3G/fzKgtK+/JmLHb9vvqOYEoGLFabvy9iY+mTtrNsgPNGLI1TR8FqRExEOqakmK+Smsv7XNVMY/sDtFwGvjNTHfX0tCJgYGyDVTBFAm/rEJl/fONNhaGdlI4R88VmZw3w1QKvMpjWrogcryvswOl+GnoWmg7klKUSDehvItC/rI=}
